POST http://localhost:8000/levels/91eb98fd-36f3-45f8-8e45-e71daf9703eb
###

GET http://localhost:8000/levels/cdbd39f5-cfa3-4db5-a3ab-5cc5796cedb1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmQzOWY1LWNmYTMtNGRiNS1hM2FiLTVjYzU3OTZjZWRiMSIsInBzZXVkbyI6Ik5lby1SeW8iLCJpYXQiOjE2MTAxMTE2OTcsImV4cCI6MTYxMDE5ODA5N30.IN4Ya34PFon28jQrMDugZHjhaXsx8YMma5QIedRTUik

###

GET http://localhost:8000/levels

###

PUT http://localhost:8000/levels/cdbd39f5-cfa3-4db5-a3ab-5cc5796cedb1/levelUp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmQzOWY1LWNmYTMtNGRiNS1hM2FiLTVjYzU3OTZjZWRiMSIsInBzZXVkbyI6Ik5lby1SeW8iLCJpYXQiOjE2MTAxMTE2OTcsImV4cCI6MTYxMDE5ODA5N30.IN4Ya34PFon28jQrMDugZHjhaXsx8YMma5QIedRTUik