POST http://localhost:8000/levels/91eb98fd-36f3-45f8-8e45-e71daf9703eb
###

GET http://localhost:8000/levels/cdbd39f5-cfa3-4db5-a3ab-5cc5796cedb1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmQzOWY1LWNmYTMtNGRiNS1hM2FiLTVjYzU3OTZjZWRiMSIsInBzZXVkbyI6Ik5lby1SeW8iLCJpYXQiOjE2MTA5Njc2NTMsImV4cCI6MTYxMTA1NDA1M30.-e5uohEyD5_ODWQqXiRPO5b_yylG56kQbiQvTMTg2TQ

###

GET http://localhost:8000/levels

###

PUT http://localhost:8000/levels/cdbd39f5-cfa3-4db5-a3ab-5cc5796cedb1/levelUp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkYmQzOWY1LWNmYTMtNGRiNS1hM2FiLTVjYzU3OTZjZWRiMSIsInBzZXVkbyI6Ik5lby1SeW8iLCJpYXQiOjE2MTA5Njc2NTMsImV4cCI6MTYxMTA1NDA1M30.-e5uohEyD5_ODWQqXiRPO5b_yylG56kQbiQvTMTg2TQ