GET http://localhost:8000/users

###

GET http://localhost:8000/users/e8a2d12b-020e-4f7b-aafd-17383e4941b6

###

POST  http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Ryo",
    "password": "toto"
}

###

POST  http://localhost:8000/users/login
Content-Type: application/json

{
    "pseudo": "Ryo",
    "password": "toto"
}

###

POST  http://localhost:8000/users/e8a2d12b-020e-4f7b-aafd-17383e4941b6/level

###
GET https://switcher-fr-api.herokuapp.com/users

###

POST https://switcher-fr-api.herokuapp.com/users
Content-Type: application/json

{
    "pseudo": "Ryo",
    "password": "toto"
}