GET http://localhost:8000/users

###

GET http://localhost:8000/users/856cec32-364f-45d0-8995-86a523f0decb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmZGUxZWI1LWM4MDgtNDczNi05NWJiLWRmODcwMzlhNDQwYyIsInBzZXVkbyI6Ik00czR0MCIsImlhdCI6MTYxMDk3NTIxMSwiZXhwIjoxNjExMDYxNjExfQ.vRxHagQXwdZC5mnsAmrJUQVN2Dw4BlKISG9yONxSf9U

###
#UserTest
GET http://localhost:8000/users/07857878-dec3-4536-a3a3-c6799799cbe7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3ODU3ODc4LWRlYzMtNDUzNi1hM2EzLWM2Nzk5Nzk5Y2JlNyIsInBzZXVkbyI6InVzZXJUZXN0IiwiaWF0IjoxNjEwOTkwODM5LCJleHAiOjE2MTEwNzcyMzl9.SYC14kJCQNdj-1xt1wyyAcXGHBPJAiXMzG1Yme617EQ

###

POST  http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Miche",
    "password": "toto"
}

###

POST  http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Toto",
    "password": "toto",
    "picture": "https://i.imgur.com/fywaJZk.jpg"
}

###

POST  http://localhost:8000/users/login
Content-Type: application/json

{
    "pseudo": "Neo-Ryo",
    "password": "toto"
}

###

POST  http://localhost:8000/users/67a6d0c4-ccdb-411c-9cd4-857ed6c49114/level

###
GET https://switcher-fr-api.herokuapp.com/users

###

POST https://switcher-fr-api.herokuapp.com/users
Content-Type: application/json

{
    "pseudo": "Ryo",
    "password": "toto"
}